name: Build & Deploy

on:
  push:
    branches: [main]   # any commit to main triggers
  workflow_dispatch:    # manual button

concurrency:
  group: prod           # only one prod deploy at a time
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, prod, linux]   # labels must match your runner
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # ── Optional guard: skip if only docs changed ──
      - name: Detect changed build‑relevant files
        id: diff
        run: |
          set -e
          BEFORE=${{ github.event.before }}
          if [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            echo "changed=yes" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          CHANGED=$(git diff --name-only "$BEFORE" ${{ github.sha }} \
            | grep -E '^(cmd/|frontend/|go\.mod|go\.sum|docker-compose\.yml)' || true)
          echo "changed=${CHANGED:-no}" >> "$GITHUB_OUTPUT"

      - if: steps.diff.outputs.changed == 'no'
        run: echo "Nothing to deploy – skipping."

      - if: steps.diff.outputs.changed != 'no'
        name: Build & restart stack
        run: |
          docker compose up -d --build --force-recreate
