name: Build & Deploy

on:
  push:
    branches: [main]   # any commit to main triggers
  workflow_dispatch:    # manual button

concurrency:
  group: prod           # only one prod deploy at a time
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, X64, Linux]   # labels must match your runner
    timeout-minutes: 30
    env:                          # ← makes them shell vars in every step
      NEXT_PUBLIC_API: ${{ secrets.NEXT_PUBLIC_API }}
      NEXT_PUBLIC_WS:  ${{ secrets.NEXT_PUBLIC_WS }}

    steps:
      - uses: actions/checkout@v4

      # ── Optional guard: skip if only docs changed ──
      - name: Detect build‑relevant changes
        id: diff
        run: |
          set -e
          BEFORE=${{ github.event.before }}
          if [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            echo "changed=yes" >>"$GITHUB_OUTPUT"
            exit 0
          fi
          if git diff --name-only "$BEFORE" ${{ github.sha }} \
              | grep -Eq '^(cmd/|frontend/|go\.mod|go\.sum|docker-compose\.yml)'; then
            echo "changed=yes" >>"$GITHUB_OUTPUT"
          else
            echo "changed=no" >>"$GITHUB_OUTPUT"
          fi

      - if: steps.diff.outputs.changed == 'no'
        run: echo "Nothing to deploy – skipping."

      - if: steps.diff.outputs.changed != 'no'
        name: Build & restart stack
        run: |
          docker compose up -d --build --force-recreate
