name: Build & Deploy

on:
  # 1️⃣  Every push to the main branch redeploys
  push:
    branches: [main]

  # 2️⃣  A manual button in the Actions tab
  workflow_dispatch:

concurrency: prod             # cancel older queued builds
jobs:
  deploy:
    runs-on: [self-hosted, prod, linux]
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4           # fresh git checkout *on the server*

      # optional – skip rebuild if only docs changed
      - name: Detect changed backend / frontend files
        id: diff
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep -E '^(cmd/|frontend/|go\.mod|go\.sum|docker-compose\.yml)')
          echo "changed=${CHANGED:-no}" >> "$GITHUB_OUTPUT"

      - if: steps.diff.outputs.changed == 'no'
        run: echo "Nothing to deploy – skipping." && exit 0

      - name: Build & restart stack
        run: |
          docker compose pull       # if you push to a registry
          docker compose up -d --build --force-recreate
